name: dev
variables:
  - name: user-service-base-url
    value: http://localhost:3002
  - name: api-gateway-base-url
    value: http://localhost:3000
  - name: access-token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWM5ZGQ0LTI2OGQtNzFjOS1iMjAxLThhMDhkZmQ2MjgwYSIsIm5hbWUiOiJEZXNtb25kIE11Y2hpY2hpbyIsInBvc2l0aW9uIjoiSVQiLCJpYXQiOjE3NzIyOTEzNDksImV4cCI6MTc3MzE5MTM0OX0.9IfN7M_KvpYRTvrqqPsxSfvbhVx5c6MUsciNnrmo5AY
